reviews:
  auto_review:
    enabled: true
  profile: "assertive"
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false

path_filters:
  exclude:
    - "**/*.md"

issues:
  collapse: false

suggestions:
  enabled: true
chat:
  auto_reply: true

language: "ko"